GET http://localhost:5000/login/username


###
POST http://localhost:5000/login/username
Content-Type: application/json

{
    "username": "hi",
    "password":"hiagain123"
}

###
POST http://localhost:5000/login 
Content-Type: application/json

{
    "username": "hi",
    "password":"hiagain123"
}

###
GET http://localhost:5000/inventory?page=5


###
GET http://localhost:5000/sort/sortByLocation?location=1.1.13

###
GET http://localhost:5000/sort/sortByUserId?userId=60c063c994a29c1da0924d7d


###
GET http://localhost:5000/localhost:5000/sort/sortByTime?time=2021-06-27T08:00:24.318+00:00
