GET http://localhost:5000/login/username


###
POST http://localhost:5000/login/username
Content-Type: application/json

{
    "username": "hi",
    "password":"hiagain123"
}

###
POST http://localhost:5000/search 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldILTJyX0hKMlY0V0laUHpsVE1rMCJ9.eyJpc3MiOiJodHRwczovL3NjaGFlZmZsZXIuanAuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MDgzMzMxOTIwMzE5NTQ1NzkxIiwiYXVkIjpbInNjaGFlZmZsZXIgaW52ZW50b3J5IGNoZWNraW5nIGFwcCIsImh0dHBzOi8vc2NoYWVmZmxlci5qcC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjMwMzU1NTA0LCJleHAiOjE2MzA0NDE5MDQsImF6cCI6IkdBaWYyQWhSRnFTaEVyU1d3eWdMMWxsRm9ZY0dQdlg5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbXX0.phN5eTwkyTJgTM-rR8XRI4o1YPX_LiUGtYXGRl42NJ6l4Yava8QfnsgBLKxIyH8ctarbYbmw0e_8OvvhjfiZ7YYADNPa_OqPI2ts17ZVifq2oUPdnpk9kHRK8DumHf93Xa4KnZPtd0IMKyjqf7l9swpiQWOKJJUPN_52KMobcjvp8b9c1rmay5focoqL-3nzdoOU3E6AnfVjtYDX7XmCWGshKb9LAfAGQ65d9SyGFZ4eB4-Mrs4fCmF_y7fMXiE8AOUxmjY-QmooChmQPxZT3e_4pl16-EmslHUs4fDU4436s4hYxb-esO3XIgoBHln9UuwjxoTJoRIh5cAkyphq8Q
{
    "userId": "blahblah",
    "keyword":"10.3.6"
}

###
GET http://localhost:5000/queue
Authorization: Bearer hello


###
GET http://localhost:5000/sort/sortByLocation?location=1.1.13

###
GET http://localhost:5000/sort/sortByUserId?userId=60c063c994a29c1da0924d7d


###
GET http://localhost:5000/queue/execute

###
DELETE http://localhost:5000/queue/delete/60f5403eb554070ba438ba28

###
GET http://localhost:5000/queue/execute/60f85150db38421a0c3ee14d
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldILTJyX0hKMlY0V0laUHpsVE1rMCJ9.eyJpc3MiOiJodHRwczovL3NjaGFlZmZsZXIuanAuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MDgzMzMxOTIwMzE5NTQ1NzkxIiwiYXVkIjpbInNjaGFlZmZsZXIgaW52ZW50b3J5IGNoZWNraW5nIGFwcCIsImh0dHBzOi8vc2NoYWVmZmxlci5qcC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjI5MTkxNzk3LCJleHAiOjE2MjkyNzgxOTcsImF6cCI6IkdBaWYyQWhSRnFTaEVyU1d3eWdMMWxsRm9ZY0dQdlg5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.Q9gmkH6gQImXBlOZfmzOLomAx4cG-GArl90qKfg4qvIM9qNs0b8fVfbPfdugyit9VW_FZsbXO6TQCs1KYX-iwWI-mtEQCoSrGotLbhiT01osxZljOEtRhP0ngPUOmt0biAao2ZKKckbkYCWLUpl1s86MHPyPj-ZrJo12pOVAG8HRm_P6g1NJ1UPHYxZUUqd0L49wAXlbUBfTlKG_SrQSsWs6sZGIRx0xPtKQuRV1uq4-DHxljYkuQ3G1pvjQCRsqLXZGL1ZYAyDSstOpD_MXJH8gQ5pT1EuYoPN-qBiifj_G1bC2wSq0DEo8xxSBG22Ceo5N8g0Yf3hEVk7jTnnTuw

###
GET http://localhost:5000/queue
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldILTJyX0hKMlY0V0laUHpsVE1rMCJ9.eyJpc3MiOiJodHRwczovL3NjaGFlZmZsZXIuanAuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MDgzMzMxOTIwMzE5NTQ1NzkxIiwiYXVkIjpbImh0dHBzOi8vc2NoYWVmZmxlci5oZXJva3VhcHAuY29tLyIsImh0dHBzOi8vc2NoYWVmZmxlci5qcC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjMxMTMyNDY0LCJleHAiOjE2MzEyMTg4NjQsImF6cCI6IkdBaWYyQWhSRnFTaEVyU1d3eWdMMWxsRm9ZY0dQdlg5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbXX0.BPsquihMa2HU3cIHwx9sIJ32Uo_mx7PT8ZG4n8ER1VDW7nw9hMlCRPZbG3iLm_qpT-YDb99W5B-LDV998HuPRZlLn8Bk48ib2Aml_jtGSaDY8Mg7H47gq60RDyo2VrHL3jWj9TJ1ZbOUXh-dAL1yHhPZbhkR09OxibgTegGh8toxdeLE_KJuzaLNrW-NJlvw7QpaYjXe5vEsaeJyxdxyLlCeUoj3juQd4O5PmU3c8z7oZ_iltDC9PSFyhl5O9XWylYGigr0CKl7N-xsXtN7w9vO2ZIx0ghToRiaWvZBMc5iz9Hm2_lbL4IVJfcfzpJ094Y22opImLBIzPRgFvnHZ_w

###
GET https://schaeffler.jp.auth0.com/api/v2/users/google-oauth2|114083331920319545791
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldILTJyX0hKMlY0V0laUHpsVE1rMCJ9.eyJpc3MiOiJodHRwczovL3NjaGFlZmZsZXIuanAuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MDgzMzMxOTIwMzE5NTQ1NzkxIiwiYXVkIjpbImh0dHBzOi8vc2NoYWVmZmxlci5oZXJva3VhcHAuY29tLyIsImh0dHBzOi8vc2NoYWVmZmxlci5qcC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjMxMTMyNDY0LCJleHAiOjE2MzEyMTg4NjQsImF6cCI6IkdBaWYyQWhSRnFTaEVyU1d3eWdMMWxsRm9ZY0dQdlg5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbXX0.BPsquihMa2HU3cIHwx9sIJ32Uo_mx7PT8ZG4n8ER1VDW7nw9hMlCRPZbG3iLm_qpT-YDb99W5B-LDV998HuPRZlLn8Bk48ib2Aml_jtGSaDY8Mg7H47gq60RDyo2VrHL3jWj9TJ1ZbOUXh-dAL1yHhPZbhkR09OxibgTegGh8toxdeLE_KJuzaLNrW-NJlvw7QpaYjXe5vEsaeJyxdxyLlCeUoj3juQd4O5PmU3c8z7oZ_iltDC9PSFyhl5O9XWylYGigr0CKl7N-xsXtN7w9vO2ZIx0ghToRiaWvZBMc5iz9Hm2_lbL4IVJfcfzpJ094Y22opImLBIzPRgFvnHZ_w